# Generated by Django 4.2.4 on 2024-08-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('img_url', models.URLField()),
                ('bought', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('MPR', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
